site_name: 07th-Mod - Developer Wiki
site_url: https://07th-mod.com
repo_url: https://github.com/07th-mod
repo_name: 07th-Mod (Organization)
copyright: All Nipahs Reserved
site_dir: developer
edit_uri: 'wiki/developer/edit/master/docs'
nav:
  - Home: index.md
  - <b>Overview</b>: overview.md
  - Patch folder structure: patch-folder-structure.md
  - Higurashi patch compiler: how-to-use-higurashi-patch-compiler.md
  - <b>Translation work</b>:
    - Resources, guidelines<br>(under construction): ./
    - Console exclusive content<br>(under construction): ./
    - Censorship, script changes<br>(under construction): ./
    - Other languages: other-languages.md
  - <b>Voice work</b>:
    - Resources, technical details: voice-details.md
    - Automated voice inserter: automated-voice-inserter.md
    - Manual work details<br>(under construction): ./
  - <b>Graphical work</b>:
    - Resources, technical details<br>(under construction): ./
    - Sunset/Night filters<br>(under construction): ./
    - MangaGamer sprites edits<br>(under construction): ./
    - Background/image panning<br>(under construction): ./
    - UI changes<br>(under construction): ./
    - UI editing scripts: ui-editing-scripts.md
  - <b>Custom game features</b>:
    - ADV Mode and LipSync: adv-mode-and-lipsync.md
  - <b>Technical engine details</b>:
    - Syntax: syntax.md
    - Assembly-CSharp.dll<br>(under construction): ./
    - Modded engine flags<br>(under construction): ./
  - <b>Patch installer</b>:
    - Technical details: technical-details.md
    - Code overview: code-overview.md
  - <b>Git and Github</b>:
    - Git Line Endings: git-line-endings.md
theme: 
  name: material
  palette:
    primary: 'brown'
    accent: 'red'
plugins:
  - search
  - minify