# This is a basic workflow to help you get started with Actions

name: Compile and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    # Runs a single command using the runners shell
    - name: install mkdocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-minify-plugin pymdown-extensions

    # Runs a set of commands using the runners shell
    - name: deploy wiki
      run: mkdocs build
    
    # Rsync repo to server, only on pushes to master (does not run on pull requests)
    - name: send to server
      uses: burnett01/rsync-deployments@4.1
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        switches: -av --delete
        path: wiki/
        remote_path: /home/07th-mod/web/wiki
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
